<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
Enter username: 
You are now logged in as testAA
User type --> Admin
Enter New Username: Enter Type of User: Enter Amount of credit for new USER: 
NOTICE: User creation sucessful!
User: testAA now logged out!
<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
TICKETING SERVICE TERMINATED!
