<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
Enter username: 
You are now logged in as testAA
User type --> Admin
Enter Username to delete: ERROR: Username "prince" does not exists in the system!
Enter Username to delete: NOTICE: User removal sucessful!
User: testAA now logged out!
<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
TICKETING SERVICE TERMINATED!
adsfads