<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
Enter username: 
You are now logged in as testAA
User type --> Admin
Enter Buyers Username: Enter Sellers Username: Enter Amount of Credit to Transfer: 
testBS to david $200.00
NOTICE: Refund successful
User: testAA now logged out!
<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
TICKETING SERVICE TERMINATED!
