<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
Enter username: 
You are now logged in as testSS
User type --> Sell Standard
Enter Event Title: Enter Sale Price of Ticket: 
Enter number of tickets: 
NOTICE: You have successfully sold ticket(s)!
User: testSS now logged out!
<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
TICKETING SERVICE TERMINATED!
