<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
Enter username: 
You are now logged in as testFS
User type --> Full Standard
Enter Event Title: Enter Sale Price of Ticket: 
Enter number of tickets: 
NOTICE: You have successfully sold ticket(s)!
User: testFS now logged out!
<------------------------- WELCOME TO THE TICKETING SERVICE! PLEASE LOG IN ------------------------->
TICKETING SERVICE TERMINATED!
